### ISSUE TITLE
Error compiling Less stylesheet: /Users/USERNAME/Library/Application Support/Mailspring/packages/isaac-dark/styles/threads.less

### ISSUE THREAD

**Issue by TheBreznsoiza** [jpminor/mailspring-isaac-dark-theme#5]
When installing the latest version there are some error messages

Error compiling Less stylesheet: /Users/USERNAME/Library/Application Support/Mailspring/packages/isaac-dark/styles/threads.less
Line number: 113
          variable @isaac-accent-light is undefined

**Comment by jpminor** [comment]
Fixed!
