### ISSUE TITLE
show icons as in default theme

### ISSUE THREAD

**Issue by fedeztk** [jpminor/mailspring-isaac-dark-theme#7]
I'm sorry for the stupid question, but how con I make the icons visible again? 
Thanks for the awesome theme by the way.

**Comment by jpminor** [comment]
Hey @fedeztk - assuming you're talking about the sidebar icons it''s in the sidebar.less file. Noted by the comment // Hide icons on line 87.  Just remove that whole section and reload the theme - you may have to make other adjustments to return to default state.

**Comment by fedeztk** [comment]
Thank you.
